// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8oHA_FIKdUthC1TdV95xI0zBU3mYsGJk',
    appId: '1:382441073285:web:4f20a4b75353b67bcf17ec',
    messagingSenderId: '382441073285',
    projectId: 'ekahanfirebase',
    authDomain: 'ekahanfirebase.firebaseapp.com',
    storageBucket: 'ekahanfirebase.appspot.com',
    measurementId: 'G-Z7JMZPE97G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqTGCnTYi3UmKyjSYhUj-hh4-d1NfFWUg',
    appId: '1:382441073285:android:5e0908f46e5faf5ecf17ec',
    messagingSenderId: '382441073285',
    projectId: 'ekahanfirebase',
    storageBucket: 'ekahanfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjFC-xZ5m8E39lnNID9i3ETC7kWv_LY7Y',
    appId: '1:382441073285:ios:76ec8b62188558f2cf17ec',
    messagingSenderId: '382441073285',
    projectId: 'ekahanfirebase',
    storageBucket: 'ekahanfirebase.appspot.com',
    iosBundleId: 'com.example.ekahanfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjFC-xZ5m8E39lnNID9i3ETC7kWv_LY7Y',
    appId: '1:382441073285:ios:552a8235197bb99acf17ec',
    messagingSenderId: '382441073285',
    projectId: 'ekahanfirebase',
    storageBucket: 'ekahanfirebase.appspot.com',
    iosBundleId: 'com.example.ekahanfirebase.RunnerTests',
  );
}
